#!/bin/bash
while true; do
  PID=$(pgrep -n "exploit|pkexec|bash")
  if [ ! -z "$PID" ]; then
    clear
    watch -n 0.1 "cat /proc/$PID/comm; grep -e 'Uid' /proc/$PID/status"
    break
  fi
  sleep 0.05
done